name = "backend"
compatibility_date = "2024-08-25"

# [vars]
# MY_VAR = "my-variable"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZmUzZDVjMTItOGUyMy00ZWQ5LWFlODItY2EwYjUzYzU0ZDRhIiwidGVuYW50X2lkIjoiZTNkMTU4MDgyYjJjZGY3ZjFmYjA1MjQ3NzhjMjZkOTgwMTc4ZTk5NzY2YmFlZmE5MDM0NjIwMzBlNDNhZDQ1YSIsImludGVybmFsX3NlY3JldCI6IjhlNzEyNDRiLWMzMWEtNDYyNy04ZmFjLWY5ZTc0ZjdjMzUxZCJ9.wS2y0YA-z3y88H1g8kCqlfF84aqat0L_EVfVXh1Jfuo"
JWT_S = "Password"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"